### ISSUE TITLE
Travis failing even after package registered

### ISSUE THREAD

**Issue by milktrader** [JuliaQuant/Timestamps.jl#1]
It was failing prior but I hoped it was because it couldn't find the package as a result of it not being registered. All tests are passing locally.

``` bash
Timestamp construction
     - fields are constructed
  Error   :: (line:-1) :: fields are constructed
    Timestamp(Date(2000,1,1),12).timestamp => Date(2000,1,1)
Timestamp not defined
```

**Comment by IainNZ** [comment]
I only quickly glanced at the tests, but I don't ever see a `using Timestamps`

**Comment by milktrader** [comment]
Thanks for the second pair of eyes!   :eyes: 

Incidentally, I tricked myself by copying the `TimeSeries/test/runtests.jl` which doesn't have a `using Timeseries` but does have a `using MarketData` that brings in the TimeSeries package.

**Comment by milktrader** [comment]
Yay, passing for `v0.4` but (sad face) not for `v0.3` because of reference to `Nullable`

Closing this and will keep troubleshooting for `v0.3`.

**Comment by aviks** [comment]
Compat.jl now had Nullable AFAIK.

**Comment by milktrader** [comment]
I was hoping to avoid that machinery since the only reference to `Nullable` is in the `show` method.

I tried a test for VERSION but it didn't work for some reason. The other _easy_ solution is to comment out the `show` method and make it `v0.3` compatible.
