### ISSUE TITLE
Implement merge method

### ISSUE THREAD

**Issue by milktrader** [JuliaQuant/Timestamps.jl#3]
Merging is actually trivial with a call to `vcat(x,y)` but this method should default to `sort=true`, which makes it more useful.

**Comment by milktrader** [comment]
https://github.com/JuliaQuant/Timestamps.jl/pull/5 starts on this, but it only includes merging two arrays of Timestamp, not individual instances.

**Comment by milktrader** [comment]
- [x] merge two Vector{Timestamp}
- [ ] merge one Vector{Timestamp} and one Timestamp
- [ ] merge one Timestamp and one Vector{Timestamp}
- [ ] merge one Timestamp and one Timestamp

**Comment by Arkoniak** [comment]
This is covered now in #14
